default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picapture_development

test:
  <<: *default
  database: picapture_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: picapture_production
  username: picapture
  password: <%= ENV['PICAPTURE_DATABASE_PASSWORD'] %>
