omniauth: &omniauth
  vk_key:    <%= ENV['VK_KEY'] %>
  vk_secret: <%= ENV['VK_SECRET'] %>
  fb_key:    <%= ENV['FB_KEY'] %>
  fb_secret: <%= ENV['FB_SECRET'] %>
  go_key:    <%= ENV['GO_KEY'] %>
  go_secret: <%= ENV['GO_SECRET'] %>

development:
  <<: *omniauth
  secret_key_base: 914db606104790e47777b06cd2128cc4a990eac900d25839407346798abd4bf005f1f2cc345d6b3a1f0511d81610e4889773dbeb783bd320e8c285a48aaab5de

test:
  <<: *omniauth
  secret_key_base: f92b48654f158714c526bfe3b5409ef67e09ba0d127ca5d2796dc73ff501ddcce656ae1cfe1a115741bd33271ce24e28e2ed98c16e1e963ef8661e71ef1d4c04

production:
  <<: *omniauth
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
